### ISSUE TITLE
sys is not defined

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [simonvh/norns#5]
I was playing around with genomepy and accidentally wiped my config.yaml clean. This gave me the error that sys was not defined:
```
Traceback (most recent call last):
  File "/home/sande/Desktop/snakemake-workflows/workflows/alignment/.snakemake/conda/a8623ecd/bin/genomepy", line 11, in <module>
    load_entry_point('genomepy==0.5.5', 'console_scripts', 'genomepy')()
  File "/home/sande/Desktop/snakemake-workflows/workflows/alignment/.snakemake/conda/a8623ecd/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/sande/Desktop/snakemake-workflows/workflows/alignment/.snakemake/conda/a8623ecd/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/sande/Desktop/snakemake-workflows/workflows/alignment/.snakemake/conda/a8623ecd/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/sande/Desktop/snakemake-workflows/workflows/alignment/.snakemake/conda/a8623ecd/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/sande/Desktop/snakemake-workflows/workflows/alignment/.snakemake/conda/a8623ecd/lib/python3.6/site-packages/genomepy/__init__.py", line 2, in <module>
    from genomepy.functions import (
  File "/home/sande/Desktop/snakemake-workflows/workflows/alignment/.snakemake/conda/a8623ecd/lib/python3.6/site-packages/genomepy/functions.py", line 13, in <module>
    from genomepy.plugin import get_active_plugins, init_plugins, activate
  File "/home/sande/Desktop/snakemake-workflows/workflows/alignment/.snakemake/conda/a8623ecd/lib/python3.6/site-packages/genomepy/plugin.py", line 7, in <module>
    config = norns.config("genomepy", default="cfg/default.yaml")
  File "/home/sande/Desktop/snakemake-workflows/workflows/alignment/.snakemake/conda/a8623ecd/lib/python3.6/site-packages/norns-0.1.4-py2.7.egg/norns/__init__.py", line 4, in config
  File "/home/sande/Desktop/snakemake-workflows/workflows/alignment/.snakemake/conda/a8623ecd/lib/python3.6/site-packages/norns-0.1.4-py2.7.egg/norns/cfg.py", line 58, in __init__
  File "/home/sande/Desktop/snakemake-workflows/workflows/alignment/.snakemake/conda/a8623ecd/lib/python3.6/site-packages/norns-0.1.4-py2.7.egg/norns/cfg.py", line 72, in load
NameError: name 'sys' is not defined
```
On this line:
https://github.com/simonvh/norns/blob/81db0004c558f91479176daf1918b8c9473b5ee2/norns/cfg.py#L72

It seems like simply adding `import sys` would solve this problem.

**Comment by Maarten-vd-Sande** [comment]
When I removed deleted my genomepy.yaml this error disappeared
